import { getLocale, getMessages } from "next-intl/server";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/providers/authProvider";
import { ChakraUIProvider } from "@/providers/chakraProvider";
import { NextIntlClientProvider } from "next-intl";
import "../index.css";
import { Header } from "@/components/ui/header";
import { ScrollToTop } from "@/components/ui/scroll-top";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages(locale);

  return (
    <html lang={locale} className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <AuthProvider>
          <ChakraUIProvider>
            <NextIntlClientProvider locale={locale} messages={messages}>
              <Header />
              {children}
              <ScrollToTop />
            </NextIntlClientProvider>
          </ChakraUIProvider>
        </AuthProvider>
      </body>
    </html >
  );
}
